### PR TITLE
A sweep on transactions docs for 7.0 release, particularly addressing…

### PR DESCRIPTION
**Pull request by programmatix**
… query and custom metadata collections.

Must be staged together with a related PR to docs-sdk-common.

### CODE REVIEW

**Comment by programmatix** [comment]
Hmm, looks like a buildbot has been added and it's being a bit annoying - yes, bulkLoadStatement is uninitialised, it's commented that the user should provide their own.

**Comment by RichardSmedley** [comment]
Hi @programmatix 
Could you do this against 3.2 please?
Then we can stage more easily,
and I'm happy to backport if you want.
(note that 3.1 generally pulls in from 6.6 common, though)

**Comment by programmatix** [comment]
Apologies, I had intended to do it on 3.2.  Will resubmit.

**Comment by programmatix** [comment]
Moved to https://github.com/couchbase/docs-sdk-java/pull/247

**Pull request closed without merging**
