### PR TITLE
Migration guide: add note about subdoc store semantics

### PR DESCRIPTION
**Pull request by dnault**
Answer the common migration question about how to migrate
MutateInBuilder.upsertDocument(true).

### CODE REVIEW

**Comment by dnault** [comment]
Did this change cause the test to fail, or are those baseline failures?

**Comment by RichardSmedley** [comment]
> Did this change cause the test to fail, or are those baseline failures?

iirc the pom.xml got moved for the txn team updates, and catching up on this change is tech debt that t he 3.3 releases have postponed us addressing.

**Comment by RichardSmedley** [comment]
> Did this change cause the test to fail, or are those baseline failures?

iirc the pom.xml got moved for the txn team updates, and catching up on this change is tech debt that t he 3.3 releases have postponed us addressing.

**Comment by maria-robobug** [comment]
Hey @dnault no, @programmatix moved the pom file awhile back, think to help IntelliJ work better with it. 
So I need to update the automation for it to run `build` and `test` checks with the new pom location.

Just haven't had the time yet, think most likely I will try to fix this tomorrow though, now that release madness has calmed down a bit 😄 .

**Review by maria-robobug — APPROVED** [review]

**Pull request merged**
