### PR TITLE
WIP sdk3 client settings

### PR DESCRIPTION
**Pull request by dnault**
Updated the overview section for SDK3's new way of configuring the cluster environment.

Updated the timeout config section.

### CODE REVIEW

**Review by RichardSmedley — COMMENTED** [review]
Looking good - thanks David :+1: 
I've tweaked one thing (callouts within the ---- listing need to be comments //).
.
btw undocumented environment settings? (line 99) - do we have many of these (or will we, once we've finished this doc)?
.
also, having removed type information for Duration (no longer a long) in the Timeout Options section (line 256, onwards), 
would it be a good idea to repeat the info from lines 92 & 93 about what goes there? (in case someone follows a link to the anchor, instead of the top of the page)
.
Anyway, great to see these things being well explained. Many thanks.

**Comment by dnault** [comment]
> btw undocumented environment settings? (line 99) - do we have many of these (or will we, once we've finished this doc)?

Heresy, I know! This TIP is perhaps not so useful to end-users. Let's delete it.

> also, having removed type information for Duration (no longer a long) in the Timeout Options section (line 256, onwards),

The type information is still there... we're just using java.util.Duration ("Duration" for short) in SDK 3 instead of longs.

> would it be a good idea to repeat the info from lines 92 & 93 about what goes there? (in case someone follows a link to the anchor, instead of the top of the page)

Yes, this would be good. Maybe with a link to the explanation instead of repeating it for every property?

**Comment by RichardSmedley** [comment]
> Yes, this would be good. Maybe with a link to the explanation instead of repeating it for every property?

Good idea :+1:

**Comment by RichardSmedley** [comment]
> > Yes, this would be good. Maybe with a link to the explanation instead of repeating it for every property?
> 
> Good idea

The following can be added to each section, where appropriate:

`See <<duration-values, setting duration values>> under xref:#system-properties[System Properties].`

**Review by RichardSmedley — APPROVED** [review]
Looking ready to merge as β doc. :+1:

**Pull request merged**
