### PR TITLE
DOC-6010 extra 3rd party licences

### PR DESCRIPTION
**Pull request by RichardSmedley**
from https://github.com/couchbase/license-reviews/tree/master/couchbase-sdk-java/3.0.0

### CODE REVIEW

**Review by daschl — CHANGES_REQUESTED** [review]
where do you get this list from? i.e. netty is missing

**Comment by RichardSmedley** [comment]
https://github.com/couchbase/license-reviews/tree/master/couchbase-sdk-java/3.0.0

**Comment by daschl** [comment]
Right, not sure what's going on there. In the last report I got with build it included netty

**Comment by RichardSmedley** [comment]
Do you have a link for that?

**Comment by RichardSmedley** [comment]
Closing, as 3rd party licences need to be a PM & legal concern.

**Pull request closed without merging**
